[template]
owner       = "haproxy"
mode        = "0644"
src         ="haproxy.cfg.tmpl"
dest        ="/etc/haproxy/haproxy.cfg"
reload_cmd  ="/usr/sbin/service haproxy reload"
keys = [
  "/services/elasticsearch",
]
